# Enable Pyflakes and pycodestyle rules.
lint.select = ["E", "F"]

# Never enforce `E501` (line length violations). E402:Module level import not at top of file
lint.ignore = ["E501", "E402","F403","F405","E722","E712"]

# Always autofix, but never try to fix `F401` (unused imports).
fix = true
# lint.unfixable = ["F401"]

# Ignore 
[lint.per-file-ignores]
"pkscreener/globals.py" =["F841", "E712"]
"pkscreener/classes/StockScreener.py" =["F841"]
"pkscreener/classes/Utility.py" = ["F401"]